name: flutter_project_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  data:
    path: ./module/data
  services:
    path: ./module/services  

  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  get: 4.2.4
  flutter: 
    sdk: flutter
  
    

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0  

flutter: 
  uses-material-design: true

