name: flutter_project_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  data:
    path: ./packages/data
  services:
    path: ./packages/services  

  cupertino_icons: ^1.0.2
  get: 4.2.4
  flutter: 
    sdk: flutter
    

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

